name: Package Application with Pyinstaller

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pyinstaller --noconfirm --onefile --windowed --add-data "/customtkinter;customtkinter/"  "run_tool.py"
    - uses: actions/upload-artifact@v2
      with:
        name: run_tool
        path: ./dist/windows